
server:
  port: 8080

netty:
  server:
    port: 9000


# redis分布式锁
redisson:
  enabled: true
  address: 'redis://10.14.2.10:6379'
  password: '123456'
  database: 0
  connectionPoolSize: 4
  connectionMinimumIdleSize: 4


spring:
  rabbitmq:
    host: 120.48.109.209
    port: 5672
    username: netty
    password: netty
    virtualHost: netty-vhost


zookeeper:
  zkServers: 120.48.109.209:2181
  connectionTimeout: 5000
